/**
 * @file bitmask_bitbound_negative.idl
 * @author Johnny Willemsen
 *
 * ridlc shall reject use of a bitmask with a negative bit_bound value
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

@bit_bound(-1)
bitmask MyBitMask {
  flag0,
  flag1,
  flag2
};
