/**
 * @file enum_bitbound_negative.idl
 * @author Johnny Willemsen
 *
 * ridlc shall reject use of a enum with a negative bit_bound value
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

@bit_bound(-1)
enum MyBitMask {
  flag0,
  flag1,
  flag2
};
