/**
 * @file map_bound_negative.idl
 * @author Johnny Willemsen
 *
 * ridlc shall reject use of a negative bound
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

typedef map<string,long,-1> StringLongMapNegative;
