/**
 * @file    test.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

enum MyEnum {
  flag0,
  flag1,
  flag2
};

@bit_bound(8)
enum MyEnumBound8 {
  flag8_1,
  flag8_2,
  flag8_3
};

@bit_bound(16)
enum MyEnumBound16 {
  flag16_1,
  flag16_2,
  flag16_3
};

@bit_bound(32)
enum MyEnumBound32 {
  flag32_1,
  flag32_2,
  flag32_3
};

enum MyValueEnum {
  @value(4) myv4,
  @value(5) myv5,
  @value(6) myv6
};

module Test
{
  interface Foo
  {
    MyEnum test_myenum (in MyEnum sin, inout MyEnum sinout, out MyEnum sout);
    MyEnumBound8 test_myenumbound8 (in MyEnumBound8 sin, inout MyEnumBound8 sinout, out MyEnumBound8 sout);
    MyEnumBound16 test_myenumbound16 (in MyEnumBound16 sin, inout MyEnumBound16 sinout, out MyEnumBound16 sout);
    MyEnumBound32 test_myenumbound32 (in MyEnumBound32 sin, inout MyEnumBound32 sinout, out MyEnumBound32 sout);
    MyValueEnum test_myvalueenum (in MyValueEnum sin, inout MyValueEnum sinout, out MyValueEnum sout);

    /// A method to shutdown the ORB
    oneway void shutdown ();
  };
};
