/**
 * @file    test.idl
 * @author  Marcel Smit
 *
 * @brief   CORBA C++11 Codec Test
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

module Test
{
  struct Bar
  {
    long A;
    long B;
    unsigned long long C;
    string D;
    wstring E;
  };

  struct Foo
  {
    wstring F;
  };
};
