/**
 * @file    anonymous_types_4.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

// Unbounded fixed constants are not supported by the C++11 mapping
const fixed pi_double = 3.142857;
