/**
 * @file    anonymous_types_2.idl
 * @author  Mark Drijver
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

module Test
{
  struct complexType
  {
    char c;
    // Anonymous type:
    sequence<char> charseq;
  };

  /// A dummy  interface for testing IDL compiler
  interface Hello
  {
    complexType get_something();

    // A method to shutdown the ORB
    oneway void shutdown ();
  };
};
