/**
 * @file    exception_attribute.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

interface intfmeth_exc_par {
  exception exc_t {
    string reason;
  };
  attribute exc_t ex;
};
