/**
 * @file    fixed_constant_scale.idl
 * @author  Johnny Willemsen
 *
 * A fixed constant with nonzero digits beyond its declared scale is illegal.
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

const fixed<20,3> invalid = 3.142857;
