/**
 * @file    module_idlkeyword.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

module Foo
{
  module MAP
  {
    struct TopicA
    {
      string a;
    };
  };
};
