/**
 * @file    positive_sequence_bound.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */

typedef sequence<long, -1> long_sequence;
