/**
 * @file    hello2.idl
 * @author  Marijke Hengstmengel
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#pragma corba_ami "Test::B"

module Test
  {
     interface A;

     interface B
      {
        long op_B (in long in_l);
      };

    interface Hello
      {
        A get_iA();
        B get_iB ();

        /// A method to shutdown the ORB
        /// This method is used to simplify the test shutdown process
        oneway void shutdown ();
      };
  };
