image:https://img.shields.io/badge/scoreboard-Remedy IT-brightgreen.svg[Scoreboard, link=https://www.taox11.org/scoreboard.html]
image:https://www.codefactor.io/repository/github/remedyit/taox11/badge[CodeFactor, link=https://www.codefactor.io/repository/github/remedyit/taox11]
image:https://github.com/RemedyIT/taox11/workflows/linux/badge.svg[Linux CI, link=https://github.com/RemedyIT/taox11/actions?query=workflow%3Alinux]
image:https://github.com/RemedyIT/taox11/workflows/windows/badge.svg[Windows CI, link=https://github.com/RemedyIT/taox11/actions?query=workflow%3Awindows]
image:https://github.com/RemedyIT/taox11/workflows/fuzzr/badge.svg[Fuzzr CI, link=https://github.com/RemedyIT/taox11/actions?query=workflow%3Afuzzr]
image:https://codecov.io/gh/RemedyIT/taox11/branch/master/graph/badge.svg[Codecov, link=https://codecov.io/gh/RemedyIT/taox11]

= TAOX11

https://www.taox11.org[TAOX11] is the https://www.omg.org/spec/CORBA[CORBA] implementation supporting the
https://www.omg.org/spec/CPP11[IDL to C++11] Language Mapping created by
https://www.remedy.nl[Remedy IT]. TAOX11 builds on the core of
https://www.remedy.nl/opensource/tao.html[TAO] to provide you with a
large set of features and capabilities. TAO is a well
known and stable CORBA implementation with a rich set of features and
capabilities.

== Install TAOX11

For installing TAOX11 you *must* use the https://github.com/RemedyIT/axcioma[AXCIOMA] bootstrap
repository. The brix11 tooling will clone this repository as part of the bootstrap step.

== Supported features

TAOX11 has the following major features:

. Compliant with the https://www.omg.org/spec/CPP11/1.4[IDL to C++11 v1.4] language mapping
. https://www.omg.org/spec/CORBA/3.3[CORBA v3.3] compliant
. Full support of the IDL type system (basic types, constant, enum, string, wide string, sequence, array, struct, union, typedef, exception)
. Full support for local and remote CORBA interfaces
. Full POA support
. Full support for valuetype and abstract interfaces
. Full support for Any
. Through POA Collocation optimization
. CORBA AMI support
. Messaging and BiDirection GIOP Policies support
. IOR Table support
. CodecFactory support
. DynamicAny and TypeCodeFactory support
. Portable Interceptors
. Experimental and partial support for https://www.omg.org/spec/IDL/4.2[IDL 4.2] map, int8/uint8, explicitly-named integer types, bitmask, bitset, empty struct, and struct inheritance extensions

