include::_{backend}_settings.adoc[]

= Manually compile TAOX11 applications

This document describes how to compile TAOX11 applications without
using MPC or BRIX11.

== IDL

As first your IDL file should be compiled into {cxx11} stub and skeleton files
(the *C.* and *S.* files). To compile a 'simple' IDL file, the following
command line options should be used when invoking the RIDL compiler.  +
 +
 Command: +
 `$X11_BASE_ROOT/bin/ridlc`  +
 +
 Command line options: +

-----------------------------------
        -Wb,pre_include=ace/pre.h
        -Wb,post_include=ace/post.h
        -I$TAOX11_ROOT
        -Sci
        -Ssi
        -Sa
        -St
        -Sp
        <idl_file>

-----------------------------------

The following {cxx11} code files will be generated by the RIDL compiler:

[cols="<,<",options="header",]
|==================================
|File name |Kind
|<idl_file>C[P].{cpp,h} |Stub files
|<idl_file>S[P].{cpp,h} |Skeleton files
|==================================

See <<ridlc.adoc#,this page>> for an explanation of the various
RIDL compiler command line options.

=== AMI

When a client needs to use <<ami/taox11_ami.adoc#,CORBA AMI>>, the following
command line options should be applied to the RIDL compiler:

-----------------------------------
        -Wb,pre_include=ace/pre.h
        -Wb,post_include=ace/post.h
        -I$TAOX11_ROOT
        -Sci
        -Ssi
        -Sa
        -St
        -GC
        <file_name>.idl

-----------------------------------

Besides the above mentioned files, the RIDL compiler will also generate
a `<idl_file>AmiC.{cpp,h}` and a `<idl_file>AmiCP.h` {cxx11} file. These files
contain all code needed for AMI, like the stub and skeleton code for the
reply handler.

== GCC command line

Once the RIDL compiler has generated the needed {cxx11} stub and skeleton
code files, the GCC-compiler should be used to create your TAOX11
application.
The GCC compiler has a lot of command line options of which TAOX11 needs
a subset. The basic command is just `{gxx}`.
Below a list of command line options which are used for every GCC
command; whether we need to link an application or compile sources,
these command line options are always applied:

-----------------------------------
        -std=c++11
        -Wno-deprecated
        -fvisibility=hidden
        -fvisibility-inlines-hidden
        -fno-strict-aliasing
        -O3
        -m64
        -pthread
        -Wall
        -W
        -Wpointer-arith
        -pipe
        -D_GNU_SOURCE
        -D__ACE_INLINE__
        -I$ACE_ROOT
        -I$TAO_ROOT
        -I$TAOX11_ROOT

-----------------------------------

Besides the above mentioned common compile options, the options below
are always applied when linking a TAOX11 application:

------------------------------------------------
        -Wl,-E
        -L.
        -L$ACE_ROOT/lib
        -L$TAOX11_ROOT/../lib
        -o <executable_name>
        .obj/<file_1>.o .. .obj/<file_n>.o
        -l<user_library_1> .. -l<user_library_n>

------------------------------------------------

Where the .o files are the object files created during the compilation
process.

== Compile TAOX11 sources

Every source file need to be compiled with the following additional
options:

-----------------------------
        -c
        -o .obj/<file_name>.o
        <file_name>.cpp

-----------------------------

See the <<Examples>> for the compilation of a
simple client and server application.

== Linking

=== Linking a TAOX11 client application

A basic TAOX11 client application needs the following libraries.

* taox11
* TAO
* ACE

So the additional compiler options are: +

----------------
        -ltaox11
        -lTAO
        -lACE
        -ldl
        -lrt

----------------

=== Linking a TAOX11 server application

A server typically need to include the `<idl_file_name>C.cpp` and the
`<idl_file_name>S.cpp` file.
 Besides these RIDL compiler generated files, a server also need to
include the servant implementation source files (if any). A basic TAOX11 server
application needs the following libraries.

* taox11_portable_server
* taox11_anytypecode
* TAO_PortableServer
* TAO_AnyTypeCode
* taox11
* TAO
* ACE

So the additional command line options are: +

--------------------------------
        -ltaox11_portable_server
        -ltaox11_anytypecode
        -lTAO_PortableServer
        -lTAO_AnyTypeCode
        -ltaox11
        -lTAO
        -lACE
        -ldl
        -lrt

--------------------------------

It is required that the order of the linked libraries is not changed.

See the <<Examples>> how to link a simple TAOX11 server
and client application.

=== Linking a TAOX11 AMI client application

Since an AMI client also functions as a server, we need to link against
the server libraries. It also need to link against the messaging
libraries because of the reply handler.

* taox11_portable_server
* taox11_messaging
* TAO_Messaging
* TAO_PI
* TAO_PortableServer
* taox11_pi
* taox11_codecfactory
* TAO_CodecFactory
* taox11_valuetype
* TAO_Valuetype
* taox11_anytypecode
* TAO_AnyTypeCode
* taox11
* TAO
* ACE

So the following command line options need to be added to the linkage
command line:  +

--------------------------------
        -ltaox11_portable_server
        -ltaox11_messaging
        -lTAO_Messaging
        -lTAO_PI
        -lTAO_PortableServer
        -ltaox11_pi
        -ltaox11_codecfactory
        -lTAO_CodecFactory
        -ltaox11_valuetype
        -lTAO_Valuetype
        -ltaox11_anytypecode
        -lTAO_AnyTypeCode
        -ltaox11
        -lTAO
        -lACE
        -ldl
        -lrt

--------------------------------

See <<Compile a simple TAOX11 AMI client,this>> for an TAOX11 AMI example.

=== Additional options

There are some additional libraries available within TAOX11, like for
instance the <<x11_logging.adoc#,TAOX11 logging library>>, which
can be used by the developers. When developers use these libraries, they
need to link against these libraries. <<lib_mpc.adoc#,This page>>
gives an overview of all additional TAOX11 libraries.

== Examples

=== Compile a simple TAOX11 client application

The main client code is written in `client.cpp` in this example. The IDL
file is called `test.idl`

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
g++ -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -I$ACE_ROOT -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -c -o .obj/client.o client.cpp
g++ -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -I$ACE_ROOT -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -c -o .obj/testC.o testC.cpp

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

=== Compile a simple TAOX11 server application

In this example the main server code is written in `server.cpp`, the
implementation of the servant has been added to `hello.cpp`, and the IDL
file is called `test.idl`

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
g++ -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -I$ACE_ROOT -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -c -o .obj/hello.o hello.cpp
g++ -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -I$ACE_ROOT -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -c -o .obj/server.o server.cpp
g++ -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -I$ACE_ROOT -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -c -o .obj/testC.o testC.cpp
g++ -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -I$ACE_ROOT -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -c -o .obj/testS.o testS.cpp

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

=== Link a simple TAOX11 client application

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
g++ -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -I$ACE_ROOT -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -m64 -Wl,-E -L$ACE_ROOT/lib -L.  -L$ACE_ROOT/lib  -L$TAOX11_ROOT/../lib  -o client .obj/client.o .obj/testC.o -ltaox11 -ltaox11_logger -lTAO -lACE -ldl -lrt

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

=== Link a simple TAOX11 server application

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
g++ -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE -I$ACE_ROOT -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -m64 -Wl,-E -L$ACE_ROOT/lib -L.  -L$ACE_ROOT/lib  -L$TAOX11_ROOT/../lib  -o server .obj/hello.o .obj/server.o .obj/testC.o .obj/testS.o -ltaox11_portable_server -ltaox11_anytypecode -lTAO_PortableServer -lTAO_AnyTypeCode -ltaox11 -ltaox11_logger -lTAO -lACE -ldl -lrt

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

=== Compile a simple TAOX11 AMI client

The main client code is written in `client.cpp` in this example. The IDL
file is called `test.idl`

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
g++ -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE   -I$ACE_ROOT -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -c -o .obj/client.o client.cpp
g++ -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE   -I$ACE_ROOT -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -c -o .obj/testC.o testC.cpp
g++ -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE   -I$ACE_ROOT -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -c -o .obj/testAmiC.o testAmiC.cpp

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

=== Link a simple TAOX11 AMI client

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
g++ -Wno-deprecated -fvisibility=hidden -fvisibility-inlines-hidden -O3 -ggdb -m64 -pthread -fno-strict-aliasing -Wall -W -Wpointer-arith -pipe -D_GNU_SOURCE   -I$ACE_ROOT -D__ACE_INLINE__ -I$ACE_ROOT -I$TAO_ROOT -I$TAOX11_ROOT -m64 -Wl,-E -L$ACE_ROOT/lib -L.  -L$ACE_ROOT/lib  -L$TAOX11_ROOT/../lib  -o client .obj/client.o .obj/testC.o .obj/testAmiC.o -ltaox11_portable_server -ltaox11_messaging -lTAO_Messaging -lTAO_PI -lTAO_PortableServer -ltaox11_pi -ltaox11_codecfactory -lTAO_CodecFactory -ltaox11_valuetype -lTAO_Valuetype -ltaox11_anytypecode -lTAO_AnyTypeCode -ltaox11 -ltaox11_logger -lTAO -lACE -ldl -lrt

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
