/**
 * @file    test.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

@cpp_mapping(STRUCT_WITH_PUBLIC_MEMBERS)
struct bar_struct {
  short b;
};

@cpp_mapping(CLASS_WITH_PUBLIC_ACCESSORS_AND_MODIFIERS)
struct bar_class {
  short b;
};

struct AA;
typedef sequence<AA> AASeq;

@cpp_mapping(STRUCT_WITH_PUBLIC_MEMBERS)
struct BB
{
  AASeq aa_;
};
typedef sequence<BB> BBSeq;

@cpp_mapping(STRUCT_WITH_PUBLIC_MEMBERS)
struct AA
{
  BBSeq bb_;
};
