/**
 * @file   ami_test_ami_stub_export.h
 * @author Marijke Hengstmengel
 *
 * @brief  CORBA C++11 ami test
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#ifndef __RIDL_AMI_TEST_AMI_STUB_EXPORT_H_EXPORT_INCLUDED__
#define __RIDL_AMI_TEST_AMI_STUB_EXPORT_H_EXPORT_INCLUDED__

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (AMI_TEST_AMI_STUB_HAS_DLL)
#  define AMI_TEST_AMI_STUB_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && AMI_TEST_AMI_STUB_HAS_DLL */

#if !defined (AMI_TEST_AMI_STUB_HAS_DLL)
#  define AMI_TEST_AMI_STUB_HAS_DLL 1
#endif /* ! AMI_TEST_AMI_STUB_HAS_DLL */

#if defined (AMI_TEST_AMI_STUB_HAS_DLL) && (AMI_TEST_AMI_STUB_HAS_DLL == 1)
#  if defined (AMI_TEST_AMI_STUB_BUILD_DLL)
#    define AMI_TEST_AMI_STUB_Export ACE_Proper_Export_Flag
#    define AMI_TEST_AMI_STUB_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define AMI_TEST_AMI_STUB_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* AMI_TEST_AMI_STUB_BUILD_DLL */
#    define AMI_TEST_AMI_STUB_Export ACE_Proper_Import_Flag
#    define AMI_TEST_AMI_STUB_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define AMI_TEST_AMI_STUB_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* AMI_TEST_AMI_STUB_BUILD_DLL */
#else /* AMI_TEST_AMI_STUB_HAS_DLL == 1 */
#  define AMI_TEST_AMI_STUB_Export
#  define AMI_TEST_AMI_STUB_SINGLETON_DECLARATION(T)
#  define AMI_TEST_AMI_STUB_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* AMI_TEST_AMI_STUB_HAS_DLL == 1 */

#endif /* __RIDL_AMI_TEST_AMI_STUB_EXPORT_H_EXPORT_INCLUDED__ */
