/**
 * @file    test.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

@default(8) typedef short short_type_8;
typedef short_type_8 typedef_short_type_8;

struct bar
{
  short short_no_default;
  @default(5) short short_5;
  short_type_8 short_8;
  typedef_short_type_8 typedef_short_8;
  @default(9) typedef_short_type_8 typedef_short_9;
  @default(5) unsigned short ushort_5;
};

exception foo
{
  short short_no_default;
  @default(5) short short_5;
  short_type_8 short_8;
  typedef_short_type_8 typedef_short_8;
  @default(9) typedef_short_type_8 typedef_short_9;
  @default(5) unsigned short ushort_5;
};
