/**
 * @file    custom_format_impl.cpp
 * @author  Unknown
 * @brief   Servant implementations
 *
 * Generated by 'brix11 generate servant' @ 2014-03-02 17:02:20 +0100
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#include "testlib/taox11_testlog.h"
//@@{__RIDL_REGEN_MARKER__} - HEADER_END : custom_format_impl.cpp[Header]

#include "custom_format_impl.h"
//@@{__RIDL_REGEN_MARKER__} - BEGIN : custom_format_impl.cpp[User Includes]
// your includes here
//@@{__RIDL_REGEN_MARKER__} - END : custom_format_impl.cpp[User Includes]

// generated from ImplSourceWriter#enter_module
namespace Test
{

  // generated from ImplSourceWriter#enter_interface

  // generated from {brix/taox11/}corba_servant/impl/src/interface_pre.erb

  //@@{__RIDL_REGEN_MARKER__} - BEGIN : Test::Foo_impl[Constructors]
  // your constructor(s)
  Foo_impl::Foo_impl (IDL::traits<CORBA::ORB>::ref_type orb)
    :  CORBA::servant_traits< ::Test::Foo>::base_type (),
       orb_ (std::move(orb))
  {
    // your constructor body
  }
  //@@{__RIDL_REGEN_MARKER__} - END : Test::Foo_impl[Constructors]

  Foo_impl::~Foo_impl ()
  {
    //@@{__RIDL_REGEN_MARKER__} - BEGIN : Test::Foo[Dtor Body]
    // your destructor body
    //@@{__RIDL_REGEN_MARKER__} - END : Test::Foo[Dtor Body]
  }

  // generated from {brix/taox11/}corba_servant/impl/src/operation.erb
  void
  Foo_impl::write_on_servant (
      const ::Test::Person& record)
  {
    //@@{__RIDL_REGEN_MARKER__} - BEGIN : Test::Foo_impl::write_on_servant[Body]
    // your code here

    TAOX11_TEST_DEBUG << "server - writing received record -> " << IDL::traits<::Test::Person>::write (record) << std::endl;

    //@@{__RIDL_REGEN_MARKER__} - END : Test::Foo_impl::write_on_servant[Body]
  }

  // generated from {brix/taox11/}corba_servant/impl/src/operation.erb
  void
  Foo_impl::shutdown ()
  {
    //@@{__RIDL_REGEN_MARKER__} - BEGIN : Test::Foo_impl::shutdown[Body]
    this->orb_->shutdown ();
    //@@{__RIDL_REGEN_MARKER__} - END : Test::Foo_impl::shutdown[Body]
  }

  // generated from {brix/taox11/}corba_servant/impl/src/interface_post.erb

  //@@{__RIDL_REGEN_MARKER__} - BEGIN : Test::Foo_impl[User Public]
  // your public implementations
  //@@{__RIDL_REGEN_MARKER__} - END : Test::Foo_impl[User Public]

  //@@{__RIDL_REGEN_MARKER__} - BEGIN : Test::Foo_impl[User Protected]
  // your protected implementations
  //@@{__RIDL_REGEN_MARKER__} - END : Test::Foo_impl[User Protected]

  //@@{__RIDL_REGEN_MARKER__} - BEGIN : Test::Foo_impl[User Private]
  // your private implementations
  //@@{__RIDL_REGEN_MARKER__} - END : Test::Foo_impl[User Private]

}; // namespace Test


//@@{__RIDL_REGEN_MARKER__} - BEGIN : custom_format_impl.cpp[Footer]
// Your footer here.
// -*- END -*-
