/**
 * @file    custom_format_impl.h
 * @author  Unknown
 * @brief   Servant implementations
 *
 * Generated by 'brix11 generate servant' @ 2014-03-02 17:02:20 +0100
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
//@@{__RIDL_REGEN_MARKER__} - HEADER_END : custom_format_impl.h[Header]

#ifndef __RIDL_CUSTOM_FORMAT_IMPL_H_INCLUDED__
#define __RIDL_CUSTOM_FORMAT_IMPL_H_INCLUDED__

#pragma once

#include "custom_formatS.h"
#include "tao/x11/orb.h"

//@@{__RIDL_REGEN_MARKER__} - BEGIN : custom_format_impl.h[User Includes]
// your includes here
//@@{__RIDL_REGEN_MARKER__} - END : custom_format_impl.h[User Includes]

// generated from ImplHeaderWriter#enter_module
namespace Test
{

  // generated from {brix/taox11/}corba_servant/impl/hdr/interface_pre.erb
  class Foo_impl
    : public CORBA::servant_traits< ::Test::Foo>::base_type
  //@@{__RIDL_REGEN_MARKER__} - BEGIN : Test::Foo_impl[Base List]
  // your base classes
  //@@{__RIDL_REGEN_MARKER__} - END : Test::Foo_impl[Base List]
  {
  public:
    //@@{__RIDL_REGEN_MARKER__} - BEGIN : Test::Foo_impl[Constructors]
    /// Constructor(s)'
    Foo_impl (IDL::traits<CORBA::ORB>::ref_type orb);
    //@@{__RIDL_REGEN_MARKER__} - END : Test::Foo_impl[Constructors]

    /// Destructor
    ~Foo_impl () override;

    //@@{__RIDL_REGEN_MARKER__} - BEGIN : Test::Foo_impl[User Protected]
    // your protected definitions
    //@@{__RIDL_REGEN_MARKER__} - END : Test::Foo_impl[User Protected]

    // generated from c++11/templates/impl/hdr/operation.erb
    /// @copydoc Test::Foo::write_on_servant
    void write_on_servant (const ::Test::Person& record) override;

    // generated from c++11/templates/impl/hdr/operation.erb
    /// @copydoc Test::Foo::shutdown
    void shutdown () override;

    // generated from {brix/taox11/}corba_servant/impl/hdr/interface_post.erb
    //@@{__RIDL_REGEN_MARKER__} - BEGIN : Test::Foo_impl[User Public]
    // your public definitions
    //@@{__RIDL_REGEN_MARKER__} - END : Test::Foo_impl[User Public]

  private:
      //@@{__RIDL_REGEN_MARKER__} - BEGIN : Test::Foo_impl[User Private]
    // your private definitions
    IDL::traits<CORBA::ORB>::ref_type orb_;
      //@@{__RIDL_REGEN_MARKER__} - END : Test::Foo_impl[User Private]


    Foo_impl (const Foo_impl&) = delete;
    Foo_impl (Foo_impl&&) = delete;
    Foo_impl& operator= (const Foo_impl&) = delete;
    Foo_impl& operator= (Foo_impl&&) = delete;
  };
}; // namespace Test


#endif /* __RIDL_CUSTOM_FORMAT_IMPL_H_INCLUDED__ */
//@@{__RIDL_REGEN_MARKER__} - BEGIN : custom_format_impl.h[Footer]
// Your footer here.
// -*- END -*-
