/**
 * @file    server.cpp
 * @author  Unknown
 * @brief   Server main
 *
 * Generated by 'brix11 generate server' @ 2014-03-02 15:41:45 +0100
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

#include "custom_formatS.h"
#include "custom_format_impl.h"

#include "testlib/taox11_testlog.h"
#include <fstream>

int
main(int argc, ACE_TCHAR *argv[])
{
  try
    {
      IDL::traits<CORBA::ORB>::ref_type _orb = CORBA::ORB_init (argc, argv);

      if (_orb == nullptr)
        {
          TAOX11_TEST_ERROR
            << "ERROR: CORBA::ORB_init (argc, argv) returned null ORB."
            << std::endl;
          return 1;
        }

      IDL::traits<CORBA::Object>::ref_type obj =
        _orb->resolve_initial_references ("RootPOA");

      if (!obj)
        {
          TAOX11_TEST_ERROR
            << "ERROR: resolve_initial_references (\"RootPOA\") returned null reference." << std::endl;
          return 1;
        }

      TAOX11_TEST_INFO << "retrieved RootPOA object reference" << std::endl;

      IDL::traits<PortableServer::POA>::ref_type root_poa =
        IDL::traits<PortableServer::POA>::narrow (obj);

      if (!root_poa)
        {
          TAOX11_TEST_ERROR
            << "ERROR: IDL::traits<PortableServer::POA>::narrow (obj) returned null object."
            << std::endl;
          return 1;
        }

      TAOX11_TEST_INFO << "narrowed POA interface" << std::endl;

      IDL::traits<PortableServer::POAManager>::ref_type poaman =
        root_poa->the_POAManager ();

      if (!poaman)
        {
          TAOX11_TEST_ERROR
            << "ERROR: root_poa->the_POAManager () returned null object."
            << std::endl;
          return 1;
        }


      CORBA::servant_traits<Test::Foo>::ref_type foo_svt =
        CORBA::make_reference<Test::Foo_impl> (_orb);

      TAOX11_TEST_INFO << "created Test::Foo servant" << std::endl;

      PortableServer::ObjectId id = root_poa->activate_object (foo_svt);

      TAOX11_TEST_INFO << "activated Test::Foo servant" << std::endl;

      obj = root_poa->id_to_reference (id);

      if (obj == nullptr)
        {
          TAOX11_TEST_ERROR
            << "ERROR: root_poa->id_to_reference (id) returned null reference."
            << std::endl;
          return 1;
        }

      IDL::traits<Test::Foo>::ref_type foo_obj =
        IDL::traits<Test::Foo>::narrow (obj);

      if (foo_obj == nullptr)
        {
          TAOX11_TEST_ERROR
            << "ERROR: IDL::traits<Test::Foo>::narrow (obj) returned null reference."
            << std::endl;
          return 1;
        }

      std::string ior = _orb->object_to_string (foo_obj);

      // Output the IOR to the <ior_output_file>
      std::ofstream fos("test.ior");
      if (!fos)
        {
          TAOX11_TEST_ERROR << "ERROR: failed to open file 'test.ior'" << std::endl;
          return 1;
        }
      fos << ior;
      fos.close ();

      TAOX11_TEST_INFO << "IOR for Test::Foo servant written to 'test.ior' : " << ior
        << std::endl;


      poaman->activate ();

      TAOX11_TEST_INFO << "starting event loop" << std::endl;

      _orb->run ();

      TAOX11_TEST_INFO << "event loop finished" << std::endl;

      root_poa->destroy (true, true);

      _orb->destroy ();
    }
  catch (const std::exception& e)
    {
      TAOX11_TEST_ERROR << "exception caught: " << e.what () << std::endl;
      return 1;
    }

  return 0;
}
