/**
 * @file    test.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

struct Point2D
{
  long x;
  long y;
};

struct Point3D : Point2D
{
  long z;
};

struct Point4D : Point3D
{
  long super;
};

struct EmptyStruct
{
};

struct DeriveEmpty : EmptyStruct
{
};

struct DeriveEmptyWithMember : EmptyStruct
{
  long x;
};

struct EmptyFromDerived : Point2D
{
};

struct EmptyFromDerivedDerived : Point3D
{
};

interface Bar
{
};

struct ObjectStruct : EmptyStruct
{
  Bar foo;
};

struct ObjectStructDerived : ObjectStruct
{
};
