/**
 * @file    test.idl
 * @author  Mark Drijver
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
  interface iA;

  interface Hello
  {
    /// Get a valid object reference
    iA get_iA();
    /// Returns a null-reference.
    iA get_null();
    /// Test in/out/return of a null-reference.
    iA inout_null(in iA in_v, out iA out_v, inout iA inout_v);

    /// A method to shutdown the ORB
    /// This method is used to simplify the test shutdown process
    oneway void shutdown ();
  };

  interface iA
  {
    string do_something_A();
  };

  typedef sequence<Object> ObjectSeq;
};
