/**
 * @file    hello2.idl
 * @author  Marijke Hengstmengel
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#pragma corba_ami "Test::B"
module Test
  {
    interface B
      {
        long op_B (in long in_l);
      };

  };
