/**
 * @file    taox11_bidir_giop_export.h
 * @author  RIDL compiler
 *
 * @brief   CORBA C++11 export file
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
#ifndef TAOX11_BIDIRGIOP_EXPORT_H
#define TAOX11_BIDIRGIOP_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (TAOX11_BIDIRGIOP_HAS_DLL)
#  define TAOX11_BIDIRGIOP_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && TAOX11_BIDIRGIOP_HAS_DLL */

#if !defined (TAOX11_BIDIRGIOP_HAS_DLL)
#  define TAOX11_BIDIRGIOP_HAS_DLL 1
#endif /* ! TAOX11_BIDIRGIOP_HAS_DLL */

#if defined (TAOX11_BIDIRGIOP_HAS_DLL) && (TAOX11_BIDIRGIOP_HAS_DLL == 1)
#  if defined (TAOX11_BIDIRGIOP_BUILD_DLL)
#    define TAOX11_BIDIRGIOP_Export ACE_Proper_Export_Flag
#    define TAOX11_BIDIRGIOP_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define TAOX11_BIDIRGIOP_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* TAOX11_BIDIRGIOP_BUILD_DLL */
#    define TAOX11_BIDIRGIOP_Export ACE_Proper_Import_Flag
#    define TAOX11_BIDIRGIOP_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define TAOX11_BIDIRGIOP_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* TAOX11_BIDIRGIOP_BUILD_DLL */
#else /* TAOX11_BIDIRGIOP_HAS_DLL == 1 */
#  define TAOX11_BIDIRGIOP_Export
#  define TAOX11_BIDIRGIOP_SINGLETON_DECLARATION(T)
#  define TAOX11_BIDIRGIOP_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* TAOX11_BIDIRGIOP_HAS_DLL == 1 */

#endif /* TAOX11_BIDIRGIOP_EXPORT_H */
