// -*- IDL -*-
/**
 * @file   test.idl
 *
 * @brief  Simple IDL file to test PortableInterceptor::Current
 *         support.
 *
 * @author  Martin Corino
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

module PICurrentTest
{
  exception bar
  {
  };

  interface test
  {
    void invoke_me ();

    void invoke_you ();

    void invoke_we ();

    void test_exception () raises (bar);

    oneway void shutdown ();
  };

};
