/**
 * @file    simple.idl
 * @author  Martin Corino
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

valuetype Bundle
{
  public long iInteger;
  void Display ();
};

interface Simple
{
  void Display (in Bundle oBundle);

  // Shutdown the remote ORB
  oneway void shutdown ();
};
