/**
 * @file    test.idl
 * @author  Marcel Smit
 *
 * @brief   Stress test for policies, using a dummy interface.
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */

interface Test
{
};
