/**
 * @file    test.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
  interface Hello;

  interface Hello_Factory
  {
    Hello get_hello ();

    void get_hello_2(out Hello hello_obj);
  };

  /// A very simple interface
  interface Hello
  {
    /// Return a simple string
    string get_string ();

    /// Return the factory for Hello
    Hello_Factory get_factory ();

    /// A method to shutdown the ORB
    /**
     * This method is used to simplify the test shutdown process
     */
    oneway void shutdown ();
  };
};
