/**
 * @file    receiver.idl
 * @author  Marcel Smit
 *
 * @brief   CORBA C++11 Multi Threaded test application
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
interface Receiver
{
  typedef sequence<octet> Payload;

  /// A simple remote call
  void receive_payload (in Receiver::Payload pay);
};
