/**
 * @file    test.idl
 * @author  Marijke Hengstmengel
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */
module A
  {
    exception DidTheRightThing {
      long id;
      string whatDidTheRightThing;
    };

    interface Test
      {
        long foo (in long in_l)
          raises (DidTheRightThing);

        attribute long yadda;

        oneway void shutdown ();
      }; //@CORBA (ami=true)
  };
