/**
 * @file    const.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

/// Put the interfaces in a module, to avoid global namespace pollution
module Test
{
  const char ch_val = 'a';
  const char ch_val_1 = '\\';
  const wchar wch_val = L'X';
  const wchar wch_val_1 = L'\\';
  const octet oct_val = 123;
  const short sh_val = -1023;
  const unsigned short ush_val = 1023;
  const long l_val = -81234;
  const unsigned long ul_val = 81234;
  const long long ll_val = -12345678;
  const unsigned long long ull_val = 12345678;
  const float f_val = 1.23;
  const double d_val = 454.23;
  const long double ld_val = 678.91;
  const boolean b_val = TRUE;
  const string s_val = "text";
  const wstring ws_val = L"widestring\n \xbf \ufe0e";
  typedef long TCounter;
  typedef string<30> TName;
  const TCounter count = 99;
  const TName name = "wilco";
  const TCounter double_count = count * 2;
  const long ALG_NONE = 0;
  const long ALG_LPC = ALG_NONE + 3;

  const long long_e1 = 2;
  const long long_e2 = long_e1 + 2;
  const long long_e3 = long_e2 * 3;
  const long long_e4 = long_e3 / 4;
  const long long_e5 = long_e4 | 5;
  const long long_e6 = long_e5 ^ 6;
  const long long_e7 = long_e6 & 7;
  const long long_e8 = long_e7 << 4;
  const long long_e9 = long_e8 >> 1;
  const long long_e10 = long_e9 % 5;
  const long long_e11 = long_e10 - 5;
  const long long_e12 = +long_e11;
  const long long_e13 = -long_e12;
  const long long_e14 = ~long_e13;
};

interface A
{
  const float pi = 3.14159;

  typedef string<5> bounded_string;
  const bounded_string bstr = "12345";
};

