/**
 * @file    test.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

struct bar
{
  short x;
  @optional short z;
  long z_long;
  @optional short a;
  @optional string opt_string;
  string y;
};

module Test
{
  interface Foo
  {
    bar test_bar (in bar bin,
      inout bar binout,
      out bar bout);

    /// A method to shutdown the ORB
    oneway void shutdown ();
  };
};
