/**
 * @file    test.idl
 * @author  Johnny Willemsen
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

struct bar
{
  short x;
  @optional short z;
  long z_long;
  @optional short a;
  @optional string opt_string;
  string y;
};
