/**
 * ****  Code generated by the RIDL Compiler ****
 * RIDL has been developed by:
 *        Remedy IT Expertise BV
 *        The Netherlands
 *        https://www.remedy.nl
 */

#define __TAOX11_INCLUDE_STUB_PROXY__

#if __has_include("tao/x11/base/tao_corba.h")
# include "tao/x11/base/tao_corba.h"
#endif
#include "tao/CDR.h"
#include "tao/x11/basic_arguments.h"
#include "tao/x11/cdr_long_double.h"
#include "tao/x11/base/tao_corba.h"

#include "testC.h"
// generated from StubProxySourceCDRWriter#pre_visit
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// generated from c++11/templates/cli/src/struct_cdr
TAO_CORBA::Boolean operator<< (TAO_OutputCDR &strm, const bar &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.x ()) &&
    (strm << _tao_aggregate.y ()) &&
    (strm << _tao_aggregate.z ()) &&
    (strm << _tao_aggregate.a ()) &&
    (strm << _tao_aggregate.opt_string ());
}

TAO_CORBA::Boolean operator>> (TAO_InputCDR &strm, bar &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.x ()) &&
    (strm >> _tao_aggregate.y ()) &&
    (strm >> _tao_aggregate.z ()) &&
    (strm >> _tao_aggregate.a ()) &&
    (strm >> _tao_aggregate.opt_string ());
}

TAO_END_VERSIONED_NAMESPACE_DECL

// -*- END -*-
