/**
 * @file    generic_servant_export.h
 * @author  Marcel Smit
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
#ifndef GENERIC_SERVANT_EXPORT_H
#define GENERIC_SERVANT_EXPORT_H

#include "tao/x11/taox11_export_macros.h"

#if defined (TAOX11_AS_STATIC_LIBS)
#  if !defined (GENERIC_SERVANT_HAS_DLL)
#    define GENERIC_SERVANT_HAS_DLL 0
#  endif /* ! GENERIC_SERVANT_HAS_DLL */
#else
#  if !defined (GENERIC_SERVANT_HAS_DLL)
#    define GENERIC_SERVANT_HAS_DLL 1
#  endif /* ! GENERIC_SERVANT_HAS_DLL */
#endif

#if defined (GENERIC_SERVANT_HAS_DLL) && (GENERIC_SERVANT_HAS_DLL == 1)
#  if defined (GENERIC_SERVANT_BUILD_DLL)
#    define GENERIC_SERVANT_Export TAOX11_Proper_Export_Flag
#    define GENERIC_SERVANT_SINGLETON_DECLARATION(T) TAOX11_EXPORT_SINGLETON_DECLARATION (T)
#    define GENERIC_SERVANT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* GENERIC_SERVANT_BUILD_DLL */
#    define GENERIC_SERVANT_Export TAOX11_Proper_Import_Flag
#    define GENERIC_SERVANT_SINGLETON_DECLARATION(T) TAOX11_IMPORT_SINGLETON_DECLARATION (T)
#    define GENERIC_SERVANT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) TAOX11_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* GENERIC_SERVANT_BUILD_DLL */
#else /* GENERIC_SERVANT_HAS_DLL == 1 */
#  define GENERIC_SERVANT_Export
#  define GENERIC_SERVANT_SINGLETON_DECLARATION(T)
#  define GENERIC_SERVANT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* GENERIC_SERVANT_HAS_DLL == 1 */

#endif /* GENERIC_SERVANT_EXPORT_H */
