/**
 * @file    PolicyS.h
 * @author  Martin Corino
 *
 * @brief   TAOX11 CORBA Policy servant
 * Handcrafted after initial generation by RIDL.
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
/*
 * ****  Code generated by the RIDL Compiler ****
 * RIDL has been developed by:
 *        Remedy IT Expertise BV
 *        Duiven, GLD
 *        The Netherlands
 *        https://www.remedy.nl
 */

#ifndef __RIDL_POLICYS_H_INCLUDED__
#define __RIDL_POLICYS_H_INCLUDED__


#endif // __RIDL_POLICYS_H_INCLUDED__

// -*- END -*-
