/**
 * @file    PolicySP.h
 * @author  Martin Corino
 *
 * @brief   TAOX11 CORBA Policy servant proxy. Dummy for compilation.
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */
/*
 * ****  Code generated by the RIDL Compiler ****
 * RIDL has been developed by:
 *        Remedy IT Expertise BV
 *        The Netherlands
 *        https://www.remedy.nl
 */

#ifndef __RIDL_POLICYSP_H_INCLUDED__
#define __RIDL_POLICYSP_H_INCLUDED__

#endif // __RIDL_POLICYSP_H_INCLUDED__

// -*- END -*-
