/**
 * @file    simple_test.idl
 * @author  Marcel Smit
 *
 * @brief   CORBA C++11 client IORTable application
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 */

module Simple
{
  interface SimpleTest
  {
    void shutdown ();
  };
};
