/**
 * @file    test.idl
 * @author  Marcel Smit
 *
 * @copyright Copyright (c) Remedy IT Expertise BV
 * Chamber of commerce Rotterdam nr.276339, The Netherlands
 */

interface test
{
  /// Returns numbers: they are constantly increasing
  long doit ();

  /// Raised if object cannot be forwarded.
  exception Cannot_Forward {};

  void forward ()
    raises (Cannot_Forward);

  oneway void shutdown ();
};
